name: Jalankan Ujian Python

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kod Kalkulator
      uses: actions/checkout@v4

    - name: Sediakan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Pasang Pytest
      run: pip install pytest

    - name: Jalankan Kod Ujian
      run: python -m pytest test_calculator.py
